### ISSUE TITLE
Get modified version of fleece to enable running in travis

### ISSUE THREAD

**Issue by hwine** [mozilla-services/fx-sig-verify#16]
[``Fleece``](https://github.com/racker/fleece) enable AWS X-Ray support, but doesn't interact with [``moto``](https://github.com/spulec/moto) well, as ``moto`` does not yet support mocking X-Ray.

Issue spulec/moto#1006 is filed for the long term fix, however it's easier to patch ``fleece``, which I've done locally. (Tracked in racker/fleece#45 and PR.)

I need to get my local changes forked and pushed to my account, so the requirements files can reference the change.

**Comment by hwine** [comment]
Closing this bug, as there is now a pip-installable version that can be used in travis:
  git+https://github.com/hwine/fleece.git@spulec_moto_1006

Still open, but no longer blocking:
 - [ ] racker/fleece#44 for the issue
 - [ ] racker/fleece#45 for the PR
 - [ ] spulec/moto#1006 for the root issue

**Comment by hwine** [comment]
This problem was mis-diagnosed, and is no longer reproducable.
