### ISSUE TITLE
Add signature for new Authenticode cert

### ISSUE THREAD

**Issue by hwine** [mozilla-services/fx-sig-verify#62]
*[See #12 for last time.]*

[Bug 1554767](https://bugzilla.mozilla.org/show_bug.cgi?id=1554767) introduces a new certificate for windows.  Get the serial number and add to code, redeploy.

**Action Plan**:
- [x] obtain new signature
- [x] add to list
- [x] add new test data
- [x] pass all local tests
- [x] pass all AWS tests
- [x] bump version & commit
- [ ] deploy to stage
- [ ] deploy to prod
