### ISSUE TITLE
Add signature for new Authenticode cert

### ISSUE THREAD

**Issue by hwine** [mozilla-services/fx-sig-verify#81]
*[See #62 for last time.]*

[Bug 1634577](https://bugzilla.mozilla.org/show_bug.cgi?id=1634577) introduces a new certificate for windows.  Get the serial number and add to code, redeploy.

**Action Plan**:
- [x] obtain new signature serial number
- [x] add new test data
- [x] verify tests fail
- [x] add new serial number to list
- [x] pass all local tests
- [x] pass all AWS tests
- [x] bump version & commit
- [x] deploy to stage
- [x] deploy to prod

**Comment by hwine** [comment]
still deploy to do

**Comment by hwine** [comment]
deployed v0.4.10 to stage to let "soak" over the long weekend

**Comment by hwine** [comment]
done long ago
