### ISSUE TITLE
Add signature for new Authenticode cert

### ISSUE THREAD

**Issue by hwine** [mozilla-services/fx-sig-verify#99]
*[See #81 for last time.]*

[Bug 1703321](https://bugzilla.mozilla.org/show_bug.cgi?id=1703321) introduces a new certificate for windows.  Get the serial number and add to code, redeploy.

**Action Plan**:
- [x] obtain new signature serial number
- [x] add new test data
- [x] verify tests fail
- [x] add new serial number to list
- [x] pass all local tests
- [x] pass all AWS tests
- [x] bump version & commit
- [x] deploy to stage
- [x] deploy to prod

**Comment by hwine** [comment]
Serial number:
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0c:1c:d3:ee:a4:7e:dd:a7:a0:32:57:3b:01:4d:0a:fd
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 Assured ID Code Signing CA
        Validity
            Not Before: Apr  9 00:00:00 2021 GMT
            Not After : Jun 19 23:59:59 2024 GMT
        Subject: C = US, ST = California, L = Mountain View, O = Mozilla Corporation, OU = Firefox Engineering Operations, CN = Mozilla Corporation
 ```

**Comment by hwine** [comment]
closed with 28b92d9f2fab585a2fd35c61d83fd7ed0a981691
